services:
  doku:
    image: amerkurev/doku
    container_name: doku
    restart: unless-stopped
    ports:
      - ${PORT}:5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostroot:ro