services:
  trudesk:
    image: polonel/trudesk:latest
    container_name: trudesk
    restart: unless-stopped
    ports:
      - ${PORT}:8118
    environment:
      - NODE_ENV=production
      - TRUDESK_DOCKER=true
      - TD_MONGODB_SERVER=mongodb
      - TD_MONGODB_DATABASE=trudesk
      - USE_XFORWARDIP=true
    volumes:
      - uploads:/usr/src/trudesk/public/uploads
      - backups:/usr/src/trudesk/backups

  mongodb:
    image: mongo:5.0-focal
    container_name: trudesk-mongodb
    restart: unless-stopped
    volumes:
      - mongodb_data:/var/lib/mongo
      - mongodb:/data/db:rw

volumes:
  uploads:
  backups:
  mongodb_data:
  mongodb:
