services:
  trudesk:
    image: polonel/trudesk:latest
    restart: unless-stopped
    ports:
      - ${PORT}:8118
    environment:
      - NODE_ENV=production
      - TRUDESK_DOCKER=true
      - TD_MONGODB_SERVER=mongodb
      - TD_MONGODB_DATABASE=trudesk
      - USE_XFORWARDIP=true
    volumes:
      - uploads:/usr/src/trudesk/public/uploads
      - backups:/usr/src/trudesk/backups

  mongodb:
    image: mongo:5.0-focal
    restart: unless-stopped
    volumes:
      - mongodb_data:/var/lib/mongo
      - mongodb:/data/db:rw

  elasticsearch:
    image: elasticsearch:8.0.0
    restart: unless-stopped
    environment:
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

volumes:
  uploads:
  backups:
  data-mongo:
  mongodb:
  elasticsearch:
